# change the following paths to your own paths
CCodePath=/data/M2PLab/data/CCode/
MCodePath=/data/M2PLab/data/MCode/

CCodePathWin=/data/M2PLab/data/CCode/
MakeTool=make -j8

CCodePathLoong=/data/M2PLab/data/CCodeLoong/
PLCCodePath=/data/M2PLab/data/PLCCode/
MfcalcCodePath=/data/M2PLab/data/mfcalcCode/
MfcalcServerPort=2003
#mode  debug  deploy
mode=debug