# change the following paths to your own paths
CCodePath=D:/M2PLab/data/CCode/
MCodePath=D:/M2PLab/data/MCode/

CCodePathWin=D:/M2PLab/data/CCode/
MakeTool=mingw32-make -j8

CCodePathLoong=D:/M2PLab/data/CCodeLoong/
PLCCodePath=D:/M2PLab/data/PLCCode/
MfcalcCodePath=D:/M2PLab/data/mfcalcCode/
MfcalcServerPort=2003
#mode  debug  deploy
mode=debug
