# change the following paths to your own paths
CCodePath=E:/m2pcode/data/CCode/
MCodePath=E:/m2pcode/data/MCode/

CCodePathWin=E:/m2pcode/data/CCode/
MakeTool=mingw32-make -j8

CCodePathLoong=E:/m2pcode/data/CCodeLoong/
PLCCodePath=E:/m2pcode/data/PLCCode/
MfcalcCodePath=E:/m2pcode/data/mfcalcCode/
MfcalcServerPort=2003
#mode  debug  deploy
mode=debug
