CCodePathWin=C:/Users/Sheng/Documents/Projects/NCSLab/NCSLabLink/CCode/

CCodePathLoong=/home/ysw/Documents/NCSLabLink/CCode/
PLCCodePath=/home/ysw/Documents/NCSLabLink/PLCCode/

CCodePath=/home/pi/NetConTop/NCSLabLink/CCode/
MCodePath=/home/pi/NetConTop/NCSLabLink/MCode/

#mode  debug  deploy
mode=debug