# change the following paths to your own paths
CCodePath=/home/square/ncslablink/CCode/
MCodePath=/home/square/ncslablink/MCode/

CCodePathWin=C:/Users/Sheng/Documents/Projects/NCSLab/NCSLabLink/CCode/

CCodePathLoong=/home/ysw/Documents/NCSLabLink/CCode/
PLCCodePath=/home/ysw/Documents/NCSLabLink/PLCCode/

#mode  debug  deploy
mode=debug
