# change the following paths to your own paths
CCodePath=/home/wenshan/NetConTop/CCode/
MCodePath=/home/wenshan/NetConTop/MCode/

CCodePathWin=E:/NetTopCon/NCSLabLink/CCode/

CCodePathLoong=/home/wenshan/NetConTop/CCodeLoong/
PLCCodePath=/home/wenshan/NetConTop/PLCCode/

#mode  debug  deploy
mode=deploy
