package com.ncslab.block.hardware.stm32;

import lombok.Getter;
import org.json.JSONObject;
import com.ncslab.dto.core.BlockDto;
import com.ncslab.dto.block.specialized.hardware.rasp.PWMDto;

import java.util.Map;
import java.util.HashMap;

import com.ncslab.block.io.InputPort;
import com.ncslab.block.io.Parameter;
import com.ncslab.code.c.CodeStructC;
import com.ncslab.code.m.CodeStructM;
import com.ncslab.ncslablink.NCSLabModel;
import com.ncslab.util.TemplateManager;

import java.util.ArrayList;
import java.util.List;

public class PWM extends com.ncslab.block.Block{

	Parameter channel;
	Parameter timx;
	Parameter frequency;
    
    
    /**
     * DTO-NATIVE Constructor - Creates PWM block directly from BlockDto DTO
     */
    public PWM(BlockDto blockDto, NCSLabModel model) {
        super(blockDto, model);
        System.out.println("DTO-NATIVE: PWM block created successfully - " + blockDto.getBlockName());
    }


    public static final List<String> inputNames = new ArrayList<>();
    
    public static final Map<String, String> PARAMETER_DEFAULTS = new HashMap<>();

    static {
        inputNames.add("in1");
        
        PARAMETER_DEFAULTS.put("PWMForStm32Channel", "1");
        PARAMETER_DEFAULTS.put("PWMForStm32TIM", "3");
        PARAMETER_DEFAULTS.put("PWMForStm32Frequency", "1000");
    }
	public PWM(JSONObject blockJSON, NCSLabModel model) {
		super(blockJSON,model);

		//һ������
		inputPortList.add(new InputPort(this,1));

		channel=new Parameter(this,1,"channel",paramValues.getString("PWMForStm32Channel"));
		timx=new Parameter(this,2,"timx",paramValues.getString("PWMForStm32TIM"));
		frequency=new Parameter(this,3,"frequency",Integer.toString(paramValues.getInt("PWMForStm32Frequency")));
	}

	public void generateInitCodeM(CodeStructM code) {
		super.generateInitCodeM(code);

		String initCode="";

//		initCode+=channel.getName()+"="+paramValues.getInt("PWMForStm32Channel")+";\n";
//
//		initCode+="TIM3_PWM_Init(2*1000000*STEP_SIZE-1,100-1,"+paramValues.getInt("PWMForStm32Channel")+");";

		code.addInitCode(initCode);
	}

	public void generateOutputCodeM(CodeStructM code) {
		super.generateOutputCodeM(code);
		String outputCode="";

		outputCode+=outputPortList.get(0).getOutputSignalC().getName()+"="+channel.getName()+";\n";

		// Removed unused outputCode reference
		 code.addOutputCode(outputCode);
	}

	public void generateInitCodeC(CodeStructC code) {
		super.generateInitCodeC(code);

		com.ncslab.util.TemplateUtils.populateAllContext(context, this);
		// Add PWM-specific variables
		context.put("channel", channel.getData().getIntValue());
		context.put("timx", timx.getData().getIntValue());
		context.put("frequency", frequency.getData().getIntValue());

		code.addInitCode(TemplateManager.renderTemplate("c/hardware/stm32/PWM/init.vm", context));
	}

	public void generateOutputCodeC(CodeStructC code) {
		com.ncslab.util.TemplateUtils.populateAllContext(context, this);
		// Add PWM-specific variables
		context.put("channel", channel.getData().getIntValue());
		context.put("timx", timx.getData().getIntValue());
		context.put("frequency", frequency.getData().getIntValue());
		// inputSignal is already populated by TemplateUtils.populatePortVariables()
		
		code.addOutputCode(TemplateManager.renderTemplate("c/hardware/stm32/PWM/output.vm", context));
	}

	@Override
	public void calculateOutput(double t) {
		// STM32 PWM hardware blocks typically don't have simulation outputs in software
		// The PWM signal is generated by the STM32 timer hardware
		if (inputPortList.size() > 0) {
			InputPort dutyCycleInput = inputPortList.get(0);
			if (dutyCycleInput.getData() != null) {
				double dutyCycle = dutyCycleInput.getData().getInitValue();
				
				// Clamp duty cycle to valid range [0, 100] or [0, 1] depending on convention
				// STM32 typically uses 0-100% range for PWM duty cycle
				if (dutyCycle < 0.0) {
					dutyCycle = 0.0;
				} else if (dutyCycle > 100.0) {
					dutyCycle = 100.0;
				}
				
				// Validate frequency parameter
				int freq = frequency.getData().getIntValue();
				if (freq <= 0) {
					// Invalid frequency, use default
					freq = 1000; // 1kHz default
				}
				
				// Validate channel parameter
				int channelNum = channel.getData().getIntValue();
				if (channelNum < 1 || channelNum > 4) {
					// Invalid channel, default to channel 1
					channelNum = 1;
				}
				
				// Validate timer parameter
				int timerNum = timx.getData().getIntValue();
				if (timerNum < 1 || timerNum > 8) {
					// Invalid timer, default to TIM3
					timerNum = 3;
				}
				
				// In simulation mode, STM32 PWM hardware blocks typically don't produce outputs
				// The hardware interface handles the actual PWM generation
				// This method serves as validation and can be extended for hardware-in-the-loop simulation
			}
		}
	}

	@Override
	public void calculateInit() {
		// Initialize STM32 PWM hardware settings
		// Validate initial parameters
		if (channel != null) {
			int channelNum = channel.getData().getIntValue();
			if (channelNum < 1 || channelNum > 4) {
				// Log warning about invalid channel
				System.err.println("Warning: Invalid PWM channel " + channelNum + ", should be 1-4");
			}
		}
		
		if (frequency != null) {
			int freq = frequency.getData().getIntValue();
			if (freq <= 0) {
				// Log warning about invalid frequency
				System.err.println("Warning: Invalid PWM frequency " + freq + ", should be > 0");
			}
		}
		
		if (timx != null) {
			int timerNum = timx.getData().getIntValue();
			if (timerNum < 1 || timerNum > 8) {
				// Log warning about invalid timer
				System.err.println("Warning: Invalid PWM timer " + timerNum + ", should be 1-8");
			}
		}
		
		// In real hardware deployment, this would configure the STM32 PWM peripheral
		// In simulation, this validates initial conditions
	}
}
